name: cron_form_field
description: >-
  A Flutter cron form field widget. It can edit cron expressions with this form field in an alert dialog.
version: 0.6.0
homepage: https://github.com/siposdani87/cron-form-field

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

topics:
  - cron
  - form-field
  - widget
  - scheduling

screenshots:
  - description: 'CronFormField picker dialog'
    path: doc/images/cron_form_field.png

repository: https://github.com/siposdani87/cron-form-field
issue_tracker: https://github.com/siposdani87/cron-form-field/issues

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: any

  flutter_lints: any

flutter:
