name: cron_form_field
description: >-
  A Flutter cron form field widget. It can edit cron expressions with this form field in an alert dialog.
version: 0.8.0
homepage: https://github.com/siposdani87/cron-form-field

environment:
  sdk: ">=3.2.1 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: any

  dart_code_metrics: any
  flutter_lints: any

flutter:
