enum CronDayType {
  EVERY_WEEK,
  EVERY_MONTH,
  EVERY_START_AT_WEEK,
  EVERY_START_AT_MONTH,
  SPECIFIC_DAY_OF_WEEK,
  SPECIFIC_DAY_OF_MONTH,
  LAST_DAY_OF_MONTH,
  LAST_WEEKDAY_OF_MONTH,
  LAST_X_DAY_OF_MONTH,
  DAY_BEFORE_END_OF_MONTH,
  NEAREST_WEEKDAY_OF_MONTH,
  XTH_DAY_OF_MONTH,
}
